name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'
          
      - name: Patch for linux build
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor
      - run: flutter build linux

      - name: Install dependencies
        run: flutter pub get

      - name: List Structure
        run: ls
#
#      - name: Creating build Directory
#        run: mkdir beta-build
#
#      - name: step 2 - Add artifacts to publish to the temp folder
#        run: |
#          cp
#
#      - name: Step 3 - Use the Upload Artifact GitHub Action
#        uses: actions/upload-artifact@v2
#        with:
#          name: assets-for-download
#          path: beta-build
